# General setup
site_name: Appyx
site_url: https://github.com/bumble-tech/appyx
site_author: Bumble
site_description: Application mechanics for your Android apps, built on top of Jetpack Compose

# Repository
repo_name: Appyx
repo_url: https://github.com/bumble-tech/appyx
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 - 2022 Bumble

# Navigation
docs_dir: documentation

nav:
  - Overview: index.md
  - Releases:
      - Downloads: releases/downloads.md
      - Changelog: releases/changelog.md
  - Using Appyx:
      - Quick start guide: how-to-use-appyx/quick-start.md
      - Codelabs: how-to-use-appyx/codelabs.md
  - Nodes and routing: basics/nodes-and-routing.md
  - Routing sources:
      - Overview: routing-sources/index.md
      - Back stack: routing-sources/backstack.md
      - Spotlight: routing-sources/spotlight.md
      - Tiles: routing-sources/tiles.md
      - Promoter: routing-sources/promoter.md
      - Writing your own: routing-sources/custom.md
  - UI:
      - Children: ui/children-view.md
      - Transitions: ui/transitions.md
  - Other topics:
      - Lifecycle: other/lifecycle.md
      - Plugins: other/plugins.md
      - Terminology: other/terminology.md


# theme configuration
theme:
  name: 'material'
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  include_search_page: false
  search_index_only: true
  features:
#    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
  palette:
    scheme: default
    primary: amber
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search

# extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
