# General setup
site_name: Appyx
site_url: https://bumble-tech.github.io/appyx/
site_author: Bumble
site_description: Model-driven navigation + UI components with gesture control for Compose Multiplatform

# Repository
repo_name: Appyx
repo_url: https://github.com/bumble-tech/appyx
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 - 2023 Bumble

# Navigation
docs_dir: documentation

nav:
  - Home: index.md
  - Appyx Navigation:
      - Overview: navigation/index.md
      - Quick start guide: navigation/quick-start.md
      - Navigation:
          - Model-driven navigation: navigation/navigation/model-driven-navigation.md
          - Composable navigation: navigation/navigation/composable-navigation.md
          - Implicit navigation: navigation/navigation/implicit-navigation.md
          - Explicit navigation: navigation/navigation/explicit-navigation.md
          - Deep linking: navigation/navigation/deep-linking.md
      - App:
          - Structuring your app navigation: navigation/apps/structure.md
          - Scoped DI: navigation/apps/scoped-di.md
          - Lifecycle: navigation/apps/lifecycle.md
          - Plugins: navigation/apps/plugins.md
          - ChildAware API: navigation/apps/childaware.md
          - Configuration changes: navigation/apps/configuration.md
      - Integrations:
          - Compose Navigation: navigation/integrations/composenavigation.md
          - Hilt: navigation/integrations/hilt.md
          - Koin: navigation/integrations/koin.md
          - Kodein: navigation/integrations/kodein.md
          - RIBs: navigation/integrations/ribs.md
          - RxJava: navigation/integrations/rx.md
          - ViewModel: navigation/integrations/viewmodel.md
  - Appyx Interactions:
    - Overview: interactions/index.md
    - Using components: interactions/usage.md
    - Creating your own:
      - Component overview: interactions/appyxcomponent.md
      - Transition model: interactions/transitionmodel.md
      - Operations: interactions/operations.md
      - UI representation: interactions/uirepresentation.md
      - KSP setup: interactions/ksp.md
      - Gestures: interactions/gestures.md
  - Appyx Components:
    - Overview: components/index.md
    - Back stack: components/backstack.md
    - Spotlight: components/spotlight.md
    - Experimental: components/experimental.md

  - Releases:
    - Downloads: releases/downloads.md
    - Changelog: releases/changelog.md
  - 2.x:
    - Migration guide: 2.x/migrationguide.md
  - 1.x:
    - Overview: 1.x/index.md
    - Releases:
      - Downloads: 1.x/releases/downloads.md
      - Changelog: 1.x/releases/changelog.md
    - Using Appyx:
        - Quick start guide: 1.x/how-to-use-appyx/quick-start.md
        - Codelabs: 1.x/how-to-use-appyx/codelabs.md
        - Coding challenges: 1.x/how-to-use-appyx/coding-challenges.md
        - Sample apps: 1.x/how-to-use-appyx/sample-apps.md
    - Navigation:
        - Model-driven navigation: 1.x/navigation/model-driven-navigation.md
        - NavModel:
            - Overview: 1.x/navmodel/index.md
            - Back stack: 1.x/navmodel/backstack.md
            - Spotlight: 1.x/navmodel/spotlight.md
            - Cards: 1.x/navmodel/cards.md
            - Tiles: 1.x/navmodel/tiles.md
            - Promoter: 1.x/navmodel/promoter.md
            - Writing your own: 1.x/navmodel/custom.md
        - Composable navigation: 1.x/navigation/composable-navigation.md
        - Implicit navigation: 1.x/navigation/implicit-navigation.md
        - Explicit navigation: 1.x/navigation/explicit-navigation.md
        - Deep linking: 1.x/navigation/deep-linking.md
    - UI:
        - Children: 1.x/ui/children-view.md
        - Transitions: 1.x/ui/transitions.md
    - App:
        - Structuring your app navigation: 1.x/apps/structure.md
        - Lifecycle: 1.x/apps/lifecycle.md
        - Plugins: 1.x/apps/plugins.md
        - ChildAware API: 1.x/apps/childaware.md
        - Configuration changes: 1.x/apps/configuration.md
    - FAQ: 1.x/faq.md
  - FAQ: faq.md


# theme configuration
theme:
  name: 'material'
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  include_search_page: false
  search_index_only: true
  features:
#    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
  palette:
    scheme: default
    primary: amber
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - include-markdown
  - macros:
      module_name: compose_mpp_sample
  - redirects:
      redirect_maps:
        'how-to-use-appyx/quick-start.md': '1.x/how-to-use-appyx/quick-start.md'
        'how-to-use-appyx/codelabs.md': '1.x/how-to-use-appyx/codelabs.md'
        'how-to-use-appyx/coding-challenges.md': '1.x/how-to-use-appyx/coding-challenges.md'
        'how-to-use-appyx/sample-apps.md': '1.x/how-to-use-appyx/sample-apps.md'
        'navigation/model-driven-navigation.md': 'navigation/navigation/model-driven-navigation.md'
        'navmodel/index.md': 'components/index.md'
        'navmodel/backstack.md': 'components/backstack.md'
        'navmodel/spotlight.md': 'components/spotlight.md'
        'navmodel/cards.md': 'components/experimental.md'
        'navmodel/tiles.md': '1.x/navmodel/tiles.md'
        'navmodel/promoter.md': '1.x/navmodel/promoter.md'
        'navmodel/custom.md': 'interactions/appyxcomponent.md'
        'navigation/composable-navigation.md': 'navigation/navigation/composable-navigation.md'
        'navigation/implicit-navigation.md': 'navigation/navigation/implicit-navigation.md'
        'navigation/explicit-navigation.md': 'navigation/navigation/explicit-navigation.md'
        'navigation/deep-linking.md': 'navigation/navigation/deep-linking.md'
        'ui/children-view.md': '1.x/ui/children-view.md'
        'ui/transitions.md': '1.x/ui/transitions.md'
        'apps/structure.md': 'navigation/apps/structure.md'
        'apps/lifecycle.md': 'navigation/apps/lifecycle.md'
        'apps/plugins.md': 'navigation/apps/plugins.md'
        'apps/childaware.md': 'navigation/apps/childaware.md'
        'apps/configuration.md': 'navigation/apps/configuration.md'
        'news.md': 'index.md'

# extensions
markdown_extensions:
  - admonition
  - pymdownx.critic
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
